#!/usr/bin/env bash
set -euo pipefail
kubectl delete -f nq/vdb-ls-nq-minilm-n1024-prep.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np64-ivf-aoff.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np64-ivf-aon.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np64-dts111-aoff.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np64-dts111-aon.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np64-dts242-aoff.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np64-dts242-aon.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np128-ivf-aoff.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np128-ivf-aon.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np128-dts111-aoff.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np128-dts111-aon.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np128-dts242-aoff.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-np128-dts242-aon.yaml || true
kubectl delete -f nq/vdb-ls-nq-minilm-aggregate.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-n4096-prep.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np128-ivf-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np128-ivf-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np128-dts111-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np128-dts111-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np128-dts242-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np128-dts242-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np256-ivf-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np256-ivf-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np256-dts111-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np256-dts111-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np256-dts242-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np256-dts242-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np512-ivf-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np512-ivf-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np512-dts111-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np512-dts111-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np512-dts242-aoff.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-np512-dts242-aon.yaml || true
kubectl delete -f dpr-w100/vdb-ls-dpr-w100-minilm-aggregate.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-n8192-prep.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np128-ivf-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np128-ivf-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np128-dts111-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np128-dts111-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np128-dts242-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np128-dts242-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np256-ivf-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np256-ivf-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np256-dts111-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np256-dts111-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np256-dts242-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np256-dts242-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np512-ivf-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np512-ivf-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np512-dts111-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np512-dts111-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np512-dts242-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np512-dts242-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np1024-ivf-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np1024-ivf-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np1024-dts111-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np1024-dts111-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np1024-dts242-aoff.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-np1024-dts242-aon.yaml || true
kubectl delete -f miracl-en/vdb-ls-miracl-en-minilm-aggregate.yaml || true
