#!/usr/bin/env bash
set -euo pipefail
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s42-prep.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s42-base.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s42-expnone.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s42-frozen.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s42-refresh.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s42-summary.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s42-prep.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s42-base.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s42-expnone.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s42-frozen.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s42-refresh.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s42-summary.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s43-prep.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s43-base.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s43-expnone.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s43-frozen.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s43-refresh.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np64-s43-summary.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s43-prep.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s43-base.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s43-expnone.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s43-frozen.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s43-refresh.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-np128-s43-summary.yaml
kubectl apply -f minilm/vdb-e2-minilm-nq-aggregate.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s42-prep.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s42-base.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s42-expnone.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s42-frozen.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s42-refresh.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s42-summary.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s42-prep.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s42-base.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s42-expnone.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s42-frozen.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s42-refresh.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s42-summary.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s43-prep.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s43-base.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s43-expnone.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s43-frozen.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s43-refresh.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np64-s43-summary.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s43-prep.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s43-base.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s43-expnone.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s43-frozen.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s43-refresh.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-np128-s43-summary.yaml
kubectl apply -f mpnet/vdb-e2-mpnet-nq-aggregate.yaml
