#!/usr/bin/env bash
set -euo pipefail
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s42-prep.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s42-base.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s42-expnone.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s42-frozen.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s42-refresh.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s42-summary.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s42-prep.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s42-base.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s42-expnone.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s42-frozen.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s42-refresh.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s42-summary.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s43-prep.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s43-base.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s43-expnone.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s43-frozen.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s43-refresh.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np64-s43-summary.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s43-prep.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s43-base.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s43-expnone.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s43-frozen.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s43-refresh.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-np128-s43-summary.yaml || true
kubectl delete -f minilm/vdb-e2-minilm-nq-aggregate.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s42-prep.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s42-base.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s42-expnone.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s42-frozen.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s42-refresh.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s42-summary.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s42-prep.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s42-base.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s42-expnone.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s42-frozen.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s42-refresh.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s42-summary.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s43-prep.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s43-base.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s43-expnone.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s43-frozen.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s43-refresh.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np64-s43-summary.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s43-prep.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s43-base.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s43-expnone.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s43-frozen.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s43-refresh.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-np128-s43-summary.yaml || true
kubectl delete -f mpnet/vdb-e2-mpnet-nq-aggregate.yaml || true
