#!/usr/bin/env bash
set -euo pipefail
kubectl delete -f nq/vdb-hn-nq-minilm-mine-s0.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-merge.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-train.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e1-np64-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e1-np64-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e1-np64-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e1-np128-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e1-np128-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e1-np128-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e2-np64-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e2-np64-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e2-np64-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e2-np128-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e2-np128-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e2-np128-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e3-np64-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e3-np64-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e3-np64-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e3-np128-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e3-np128-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e3-np128-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e5-np64-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e5-np64-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e5-np64-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e5-np128-ivf.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e5-np128-dts111.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-e5-np128-dts242.yaml || true
kubectl delete -f nq/vdb-hn-nq-minilm-aggregate.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s0.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s1.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s2.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s3.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s4.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s5.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s6.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-mine-s7.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-merge.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-train.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np128-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np128-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np128-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np256-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np256-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np256-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np512-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np512-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e1-np512-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np128-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np128-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np128-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np256-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np256-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np256-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np512-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np512-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e2-np512-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np128-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np128-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np128-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np256-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np256-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np256-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np512-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np512-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e3-np512-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np128-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np128-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np128-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np256-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np256-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np256-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np512-ivf.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np512-dts111.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-e5-np512-dts242.yaml || true
kubectl delete -f dpr-w100/vdb-hn-dpr-w100-minilm-aggregate.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s0.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s1.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s2.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s3.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s4.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s5.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s6.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-mine-s7.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-merge.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-train.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np128-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np128-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np128-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np256-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np256-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np256-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np512-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np512-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np512-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np1024-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np1024-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e1-np1024-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np128-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np128-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np128-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np256-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np256-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np256-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np512-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np512-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np512-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np1024-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np1024-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e2-np1024-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np128-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np128-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np128-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np256-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np256-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np256-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np512-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np512-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np512-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np1024-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np1024-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e3-np1024-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np128-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np128-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np128-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np256-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np256-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np256-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np512-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np512-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np512-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np1024-ivf.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np1024-dts111.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-e5-np1024-dts242.yaml || true
kubectl delete -f miracl-en/vdb-hn-miracl-en-minilm-aggregate.yaml || true
